name: gtf
version: 0.0.1
output_asset_class: gtf
description: GTF annotation asset which provides access to all annotated transcripts
inputs:
  files:
    gtf:
      description: Annotation file in Gene Transfer Format (GTF) from Gencode
  params: {}
  assets: {}
container: databio/refgenie
command_template_list:
- cp {{files.gtf}} {{asset_outfolder}}/{{genome}}.gtf.gz
custom_properties: {}
default_tag: default
